### ISSUE TITLE
Valet secure

### ISSUE THREAD

**Issue by LaurenaRehbein** [SystmWeb/valetpress#4]
Any thoughts on how I can incorporate valet secure into the process to serve the new site over `https`?

**Comment by sdenike** [comment]
@LaurenaRehbein sure! I was thinking about adding this via the config file, or would you think it would be better as an option during the install of WordPress?

**Comment by LaurenaRehbein** [comment]
Typically, I want my test sites secure, but there could very likely be a use for an insecure setup on occasion as well. 

Might be more useful as an option, presented to the user during the setup. That would be slick!

**Comment by sdenike** [comment]
I will try to roll this into the next release when I have some time to make some other changes. Thanks again for the feedback!
